imports_granularity = "Item"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
imports_layout = "Vertical"

tab_spaces = 3
hard_tabs = false

blank_lines_upper_bound = 1

chain_width = 100
max_width = 200

reorder_impl_items = true


brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

empty_item_single_line = true
fn_single_line = false
where_single_line = true

format_strings = true

match_block_trailing_comma = true

normalize_comments = true
combine_control_expr = false

single_line_if_else_max_width = 0
single_line_let_else_max_width = 0

struct_field_align_threshold = 100
struct_lit_single_line = true

trailing_comma = "Never"
trailing_semicolon = true
use_field_init_shorthand = true

