[package]
name = "window"
version = "0.1.0"
edition = "2021"

[lib]
name = "window"
path = "lib.rs"

[dependencies]
opencv = "0.91.3"
tokio = { version = "1.37.0", features = ["full"] }
winapi = { version = "0.3.9", features = ["windef", "winuser"]}
